name: CI
on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - authorization-agent
          - application
          - data-model
          - test-utils
          - utils
          - service
          - api-messages
    steps:
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Modify .npmrc
        run: echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}' >> .npmrc
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpx turbo run build
      - name: Run tests
        working-directory: ./packages/${{ matrix.package }}
        run: pnpm run test
      - name: Submit code coverage
        uses: codecov/codecov-action@v4
        with:
          flags: ${{ matrix.package }}
          directory: ${{ github.workspace }}/packages/${{ matrix.package }}/coverage
